logo: # add logo name
title: GreenMindLabs - Security
description: > # this means to ignore newlines until "baseurl:"
  Olá eu sou o GreenMind , apaixonado e amante da tecnologia tenho como meta compartilhar o meu dia a dia e tentar ajudar pessoas que assim como eu também está iniciando nessa loucura que é o mundo l33t.

permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aluno-green.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: # your name
about-author: # about author
email: greenmind.sec@gmail.com # your email
phone: (496)-169-6557 # your pnone number
website: https://greenmindlabs.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: disqus_xSFYhuvxla # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
